### ISSUE TITLE
wpa_networks: A list of network dicts, see molecule/default/playbook.yml for examples

### ISSUE THREAD

**Issue by kewlfft** [WanderlandTravelers/ansible-wpa_supplicant-role#1]
it says
wpa_networks: A list of network dicts, see molecule/default/playbook.yml for examples. 
but couldn't find any

**Comment by brad** [comment]
@kewlfft Sorry about that. They are [here](https://github.com/WanderlandTravelers/ansible-wpa_supplicant-role/blob/master/molecule/options/playbook.yml#L15), I need to update that comment:
```
        wpa_networks:
          - ssid: test
            psk: testtest
            priority: 1
            id_str: testOne
          - ssid: test2
            psk: testtest2
            priority: 2
            id_str: testTwo
          - ssid: testing
            key_mgmt: NONE
          - ssid: yourHiddenSSID
            scan_ssid: 1
            psk: Your_wifi_password
          - ssid: 1x-test
            scan_ssid: 1
            key_mgmt: IEEE8021X
            eap: TLS
            identity: user@example.com
            ca_cert: /etc/cert/ca.pem
            client_cert: /etc/cert/user.pem
            private_key: /etc/cert/user.prv
            private_key_passwd: password
            eapol_flags: 3
```
